# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ah1n3jP9TWieji38KkYgRcCfwsQqd8c3

PERFORMING EXPLORATORY DATA ANALYSIS ON GIVEN DATA

IMPORTING LIBRARIES
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""CALLING FILE"""

df=pd.read_csv("psg.csv")

"""TAKING FIRST 1000 DATA"""

th=df.head(1000)

ps=th.head(100)

"""TAKING FIRST 5 DATA USING HEAD() FUNCTION"""

ps.head()

"""TAKING LAST 5 DATA USING TAIL()"""

ps.tail()

"""DESCRIPTION OF DATA USING DESCRIBE()  FUNCTION"""

ps.describe()

"""OBSERVING INFORMATION (NULLNESS,DATATYPE) USING INFO()

"""

ps.info()

"""KNOWING NO. OF ROWS AND COLUMNS USING SHAPE"""

ps.shape

"""KNOWING NAME OF COLUMNS USING COLUMNS"""

ps.columns

"""KNOWING NO. OF UNIQUE DATA IN COLUMNS USING NUNIQUE()"""

hd.nunique()

"""CHECKING NULLNESS"""

ps.isnull()

hd.isnull().sum()

"""DIFFERENT TYPES OF PLOTS"""

plt.scatter(x,y)
plt.xlabel('usg_wac')
plt.ylabel('fg_wac')
plt.show
plt.title("passanger scatter plot")

hd.plot()
plt.title("passanger hd plot")

plt.hist(a)
plt.show
plt.title("passanger histogram plot")

ps.plot.box()
plt.title("passanger box plot")

hd.plot.area()
plt.title("passanger hd area plot")

plt.title("passanger stem plot")
plt.stem(a)
plt.show

plt.title("passanger pie chart")
plt.pie(a)
plt.show

plt.title("passanger polar")
plt.polar(a)
plt.show

